import React, { useContext } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Context } from '../context/context'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Top from '../components/top'


export default function About() {
  const { darkMode } = useContext(Context)
  return (
    <div className={`min-h-screen w-full ${darkMode ? 'bg-gradient-to-r from-[#1a1807] to-gray-900 text-yellow-400' : 'bg-gradient-to-r from-purple-300 to-white text-purple-600'}`}>
      <div className='max-w-7xl w-full mx-auto'>

      <Top />
      <Head>
        <title>sambhav-kaushik-home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${darkMode ? '/yellow.svg' : '/purple.svg'}`} />
      </Head>

      <Navbar active={'about'}/>

      <main className='w-full min-h-screen flex items-center'>
      <div id='about' className="w-full overflow-hidden mb-10 flex sm:flex-row flex-col">
          <div className="my-auto flex flex-col justify-start px-10 py-5 w-full sm:w-1/2">
          <h1 className="text-3xl sm:text-4xl font-bold mb-4 hover:scale-x-105 transition-all duration-300 ease-out cursor-pointer">Who am I?</h1>
            <div className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.
            <div className="w-full max-w-sm mx-auto sm:hidden block py-5">
            <img src={'/favicon.ico'} alt="" className='w-full' />
          </div>
            I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a ni...</span></div>
          </div>
          <div className="sm:block hidden w-1/2 px-10 py-5">
            <img src={'/favicon.ico'} alt="" className='w-full' />
          </div>
        </div>
      </main>

      <Footer/>

      </div>

    </div>
  )
}