import React, { useContext } from 'react'
import { Context } from '../context/context'
import Head from 'next/head'
import Bg from '../components/Bg'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import BlogCard from '../components/blogCard'
import { Wave } from '../components/Svgs'

const Blog = () => {

    const {darkMode, projectItemRef} = useContext(Context)

  return (
    <div className={`${darkMode?'dark-scroll':'light-scroll'}`}>

      <Head>
        <title>sambhav-kaushik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${darkMode ? '/teal.svg' : '/purple.svg'}`} />
      </Head>

      {/* bg */}
      <Bg />
      <Wave />

      {/* app  */}
      <div className={`relative z-10 min-h-screen w-full transition-all duration-300 ease-in-out ${darkMode ? 'text-teal-500' : 'text-purple-600'}`}>

        <div className="max-w-7xl w-full mx-auto">

          <Navbar active={'home'} />

          <main className='w-full min-h-screen transition-all duration-300 ease-in-out'>

          <div id='project' className="w-full pt-10 mb-10 overflow-hidden flex flex-col justify-center min-h-screen">
              <h1 className="text-2xl sm:text-4xl text-center font-bold mb-4 my-5">Blogs</h1>
              <div ref={projectItemRef} className="px-10 pb-5 w-full">

                <section className={`${darkMode ? 'text-white' : 'text-gray-900'} body-font`}>
                  <div className="w-full px-5 py-4 mx-auto">
                    <div className="flex flex-wrap -m-4">

                      <BlogCard />
                      <BlogCard />
                      <BlogCard />
                      <BlogCard />
                      <BlogCard />
                      <BlogCard />

                    </div>
                  </div>
                </section>

              </div>
            </div>


          </main>
        </div>

        <Footer />

      </div>

    </div>
  )
}

export default Blog