import React, { useContext } from 'react'
import Head from 'next/head'
import { Context } from '../context/context'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Top from '../components/top'
import { Doughnut } from 'react-chartjs-2';



export default function Experience() {
  const dataPie = {
    labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    datasets: [
      {
        label: '# of Votes',
        data: [12, 19, 3, 5, 2, 3],
        backgroundColor: [
          'rgba(255, 99, 132, 0.5)',
          'rgba(54, 162, 235, 0.5)',
          'rgba(255, 206, 86, 0.5)',
          'rgba(75, 192, 192, 0.5)',
          'rgba(153, 102, 255, 0.5)',
          'rgba(255, 159, 64, 0.5)',
        ],
        borderColor: [
          'rgba(255, 99, 132, 0.5)',
          'rgba(54, 162, 235, 0.5)',
          'rgba(255, 206, 86, 0.5)',
          'rgba(75, 192, 192, 0.5)',
          'rgba(153, 102, 255, 0.5)',
          'rgba(255, 159, 64, 0.5)',
        ],
        borderWidth: 1,
      },
    ],
  };

  const { darkMode, router } = useContext(Context)

  return (
    <div className={`min-h-screen w-full ${darkMode ? 'bg-gradient-to-r from-[#1a1807] to-gray-900 text-yellow-400' : 'bg-gradient-to-r from-purple-300 to-white text-purple-600'}`}>
      <div className="max-w-7xl w-full mx-auto">

        <Top />
        <Head>
        <title>sambhav-kaushik-home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${darkMode ? '/yellow.svg' : '/purple.svg'}`} />
      </Head>

        <Navbar active={'experience'} />

        <main className='w-full min-h-screen flex items-center'>
          {/* experience  */}
          <div id='experience' className=" w-full mb-10 overflow-hidden flex sm:flex-row sm:items-center flex-col">
            <div className="w-full sm:w-2/3 px-10 py-5">
              <div className=''>
                <h1 className="sm:text-4xl text-3xl font-bold mb-4 hover:scale-x-105 transition-all duration-300 ease-out cursor-pointer">Experience {'&'} skills</h1>
                <div className="text-sm sm:text-base"><span className={`${darkMode ? 'text-white' : 'text-black'}`}>HTML, CSS, Bootstrap, TailwindCSS, MaterialUI, JavaScript, Python, ReactJS, NextJS, Strpi, ExpressJS, Django, Flask, PostgreDB, MongoDB, Mongoose, Block Chain, Ethereum, Polygon, Solidity, Rust, JSON, SanityDB, GROQ, Java, Pandas, Logo designing, Blender 3D, Animation, UX/UI designing and many more. Lorem ipsum dolor sit amet
                <div className="w-full sm:hidden block py-5 max-w-sm mx-auto">
                <Doughnut className='hover:scale-105 transition-all duration-300 ease-out' data={dataPie} />
              </div>
               consectetur adipisicing elit. Inventore in iste, esse sunt ut, quas culpa harum laborum fugiat, nisi eos sequi maxime odio? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, incidunt beatae dicta assumenda harum ipsa reiciendis enim sequi rem quia corporis magnam, rerum impedit fuga alias adipisci hic unde veritatis! Voluptatem quod sit soluta sapiente atque praesentium exercitationem illum corrupti?
              <div className={`w-full py-5 ${darkMode ? 'text-white' : 'text-black'} sm:hidden block`}>
                <div className="flex flex-col w-full">
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Front-end development</p>
                    <div className={`w-10/12 bg-green-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Back-end development</p>
                    <div className={`w-full bg-red-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">App development</p>
                    <div className={`w-11/12 bg-cyan-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Logo designing</p>
                    <div className={`w-9/12 bg-violet-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">3D modelling</p>
                    <div className={`w-8/12 bg-orange-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                </div>
              </div>
               Molestias a molestiae minus dolorum odit, obcaecati perspiciatis voluptatem cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt quas expedita sed nesciunt, ipsam nisi ab, labore praesentium aspernatur, earum cupiditate ad vero veritatis. Quia repellat sunt suscipit quas sed commodi earum fuga quibusdam quo, impedit voluptates aliquid mollitia repudiandae autem ex illum blanditiis nesciunt incidunt dolorem beatae, possimus perspiciatis?</span></div>
              </div>

              <div className={`w-full mt-8 ${darkMode ? 'text-white' : 'text-black'} sm:block hidden`}>
                <div className="flex flex-col w-full">
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Front-end development</p>
                    <div className={`w-10/12 bg-green-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Back-end development</p>
                    <div className={`w-full bg-red-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">App development</p>
                    <div className={`w-11/12 bg-cyan-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Logo designing</p>
                    <div className={`w-9/12 bg-violet-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">3D modelling</p>
                    <div className={`w-8/12 bg-orange-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-row sm:flex-col justify-start items-start px-10 py-5 w-full sm:w-1/3">
              <div className="w-full hidden sm:block">
                <Doughnut className='hover:scale-105 transition-all duration-300 ease-out' data={dataPie} />
              </div>
            </div>
          </div>
        </main>

        <Footer />

      </div>
    </div>
  )
}