import React, { useContext, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Context } from '../context/context'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Typewriter from 'typewriter-effect';
import Top from '../components/top'
import Bg from '../components/bg'
import { Doughnut } from 'react-chartjs-2'
import { Wave } from '../components/svgs'
import {motion , useAnimation} from 'framer-motion'
import { useInView } from 'react-hook-inview'


export default function Home() {
  const dataPie = {
    labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    datasets: [
      {
        label: '# of Votes',
        data: [12, 19, 3, 5, 2, 3],
        backgroundColor: [
          'rgba(255, 99, 132, 0.5)',
          'rgba(54, 162, 235, 0.5)',
          'rgba(255, 206, 86, 0.5)',
          'rgba(75, 192, 192, 0.5)',
          'rgba(153, 102, 255, 0.5)',
          'rgba(255, 159, 64, 0.5)',
        ],
        borderColor: [
          'rgba(255, 99, 132, 0.5)',
          'rgba(54, 162, 235, 0.5)',
          'rgba(255, 206, 86, 0.5)',
          'rgba(75, 192, 192, 0.5)',
          'rgba(153, 102, 255, 0.5)',
          'rgba(255, 159, 64, 0.5)',
        ],
        borderWidth: 1,
      },
    ],
  };

  const { darkMode, router, setIsLoading, aboutImgAnimation, aboutImgRef, aboutTextAnimation, aboutTextRef } = useContext(Context)

  return (
    <>
      <Head>
        <title>sambhav-kaushik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${darkMode ? '/yellow.svg' : '/purple.svg'}`} />
      </Head>

      {/* top */}
      <Top />

      {/* bg */}
      <Bg />

      {/* design  */}
      <Wave/>

      {/* app  */}
      <div className={`relative z-10 min-h-screen w-full transition-all duration-300 ease-in-out ${darkMode ? 'text-teal-500' : 'text-purple-600'}`}>

        <div className="max-w-7xl w-full mx-auto">

          <Navbar active={'home'} />

          <main className='w-full min-h-screen transition-all duration-300 ease-in-out'>

            {/* cover */}
            <div id='cover' className="w-full mb-10 mt-5 flex sm:flex-row sm:items-center sm:justify-evenly justify-center flex-col min-h-screen">

              <motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{duration:0.3}} className="flex text-3xl font-bold sm:text-4xl flex-col justify-center px-10 py-5 w-full sm:w-1/2">

                <div className={`transition-all duration-300 ease-out`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>Hi, I'm </span>Sambhav Kaushik</div>
                <div className={`transition-all duration-300 ease-out`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I'm a </span><Typewriter
                  options={{
                    strings: ['Full-stack Web developer', 'UI/UX designer', 'App developer', 'Data manager', 'Logo designer', '3-D modeler', 'Animator'],
                    autoStart: true,
                    loop: true,
                  }}
                /></div>

              </motion.div>
              <div className="w-full sm:w-1/2 py-5 max-w-sm mx-auto px-10">
                <motion.img initial={{scale:0}} animate={{scale:1}} transition={{duration:0.3}} src={'/photo2.jpg'} alt="" className='w-full' />
              </div>
            </div>

            {/* semi-about  */}
            <div id='about' className="w-full mb-10 flex items-center justify-center sm:flex-row flex-col min-h-screen">

              <motion.div ref={aboutImgRef} animate={aboutImgAnimation} className={`sm:w-1/2 w-11/12 mx-auto p-10 border-b border-l ${darkMode?'border-teal-500':'border-purple-600'}  max-w-sm mx-auto`}>
                <img className={`w-full rounded-lg`} src={'/photo2.jpg'} alt="" />
              </motion.div>

              <div ref={aboutTextRef} className={`w-full sm:w-1/2`}>
              <motion.div ref={aboutTextRef} animate={aboutTextAnimation} className="my-auto flex flex-col justify-start px-10 py-5 w-full">
                <h1 className="text-3xl sm:text-4xl font-bold mb-4 transition-all duration-300 ease-out">Get to know me!</h1>
                <p className={`text-sm sm:text-base transition-all duration-300 ease-out`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a ni. <br/> Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a ni.</span></p>
              </motion.div>
              </div>
            </div>

            {/* semi-experience  */}
            {/* <div id='experience' className=" w-full mb-20 overflow-hidden flex flex-col justify-center min-h-screen">
              <h1 className="text-3xl sm:text-4xl text-center font-bold mb-4 hover:scale-x-105 transition-all duration-300 ease-out cursor-pointer">What I know?</h1>
              <div className="flex sm:flex-row flex-col items-center justify-evenly px-10 pb-5 w-full">
                <div className="w-full sm:w-1/3 sm:max-w-full max-w-sm sm:mx-auto mx-auto">
                  <Doughnut className='hover:scale-105 transition-all duration-300 ease-out' data={dataPie} />
                </div>
                <div className={`w-full sm:w-2/3 ${darkMode ? 'text-white' : 'text-black'}`}>
                  <div className={`w-full mt-8 ${darkMode ? 'text-white' : 'text-black'}`}>
                    <div className="flex flex-col w-full">
                      <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">Front-end development</p>
                        <div className={`w-10/12 bg-green-500 h-0.5 transition-all duration-300`}></div>
                      </div>
                      <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">Back-end development</p>
                        <div className={`w-full bg-red-500 h-0.5 transition-all duration-300`}></div>
                      </div>
                      <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">App development</p>
                        <div className={`w-11/12 bg-cyan-500 h-0.5 transition-all duration-300`}></div>
                      </div>
                      <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">Logo designing</p>
                        <div className={`w-9/12 bg-violet-500 h-0.5 transition-all duration-300`}></div>
                      </div>
                      <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">3D modelling</p>
                        <div className={`w-8/12 bg-orange-500 h-0.5 transition-all duration-300`}></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="w-full px-10">
                <p className="text-sm sm:text-base"><span className="font-bold">Skill set: </span><span className={`${darkMode ? 'text-white' : 'text-black'}`}>HTML, CSS, Bootstrap, TailwindCSS, MaterialUI, JavaScript, Python, ReactJS, NextJS, Strpi, ExpressJS, Django, Flask, PostgreDB, MongoDB, Mongoose, Block Chain, Ethereum, Polygon, Solidity, Rust, JSON, SanityDB, GROQ, Java, Pandas, Logo designing, Blender 3D, Animation, UX/UI designing... <a onClick={() => {
                  setIsLoading(true)
                  setTimeout(() => {
                    router.push('/experience')
                  }, 500);
                }} className={`${darkMode ? 'text-yellow-400' : 'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Read More</a></span></p>
              </div>
            </div> */}
            <div id='experience' className=" w-full mb-10 overflow-hidden flex sm:flex-row sm:items-center flex-col">
            <div className="w-full sm:w-2/3 px-10 py-5">
              <div className=''>
                <h1 className="sm:text-4xl text-3xl font-bold mb-4 hover:scale-x-105 transition-all duration-300 ease-out cursor-pointer">Experience {'&'} skills</h1>
                <div className="text-sm sm:text-base"><span className={`${darkMode ? 'text-white' : 'text-black'}`}>HTML, CSS, Bootstrap, TailwindCSS, MaterialUI, JavaScript, Python, ReactJS, NextJS, Strpi, ExpressJS, Django, Flask, PostgreDB, MongoDB, Mongoose, Block Chain, Ethereum, Polygon, Solidity, Rust, JSON, SanityDB, GROQ, Java, Pandas, Logo designing, Blender 3D, Animation, UX/UI designing and many more. Lorem ipsum dolor sit amet
                <div className="w-full sm:hidden block py-5 max-w-sm mx-auto">
                <Doughnut className='hover:scale-105 transition-all duration-300 ease-out' data={dataPie} />
              </div>
               consectetur adipisicing elit. Inventore in iste, esse sunt ut, quas culpa harum laborum fugiat, nisi eos sequi maxime odio? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, incidunt beatae dicta assumenda harum ipsa reiciendis enim sequi rem quia corporis magnam, rerum impedit fuga alias adipisci hic unde veritatis! Voluptatem quod sit soluta sapiente atque praesentium exercitationem illum corrupti?
              <div className={`w-full py-5 ${darkMode ? 'text-white' : 'text-black'} sm:hidden block`}>
                <div className="flex flex-col w-full">
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Front-end development</p>
                    <div className={`w-10/12 bg-green-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Back-end development</p>
                    <div className={`w-full bg-red-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">App development</p>
                    <div className={`w-11/12 bg-cyan-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Logo designing</p>
                    <div className={`w-9/12 bg-violet-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">3D modelling</p>
                    <div className={`w-8/12 bg-orange-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                </div>
              </div>
               Molestias a molestiae minus dolorum odit, obcaecati perspiciatis voluptatem cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt quas expedita sed nesciunt, ipsam nisi ab, labore praesentium aspernatur, earum cupiditate ad vero veritatis. Quia repellat sunt suscipit quas sed commodi earum fuga quibusdam quo, impedit voluptates aliquid mollitia repudiandae autem ex illum blanditiis nesciunt incidunt dolorem beatae, possimus perspiciatis?</span></div>
              </div>

              <div className={`w-full mt-8 ${darkMode ? 'text-white' : 'text-black'} sm:block hidden`}>
                <div className="flex flex-col w-full">
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Front-end development</p>
                    <div className={`w-10/12 bg-green-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Back-end development</p>
                    <div className={`w-full bg-red-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">App development</p>
                    <div className={`w-11/12 bg-cyan-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">Logo designing</p>
                    <div className={`w-9/12 bg-violet-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                  <div className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                    <p className="mb-2">3D modelling</p>
                    <div className={`w-8/12 bg-orange-500 h-0.5 transition-all duration-300`}></div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-row sm:flex-col justify-start items-start px-10 py-5 w-full sm:w-1/3">
              <div className="w-full hidden sm:block">
                <Doughnut className='hover:scale-105 transition-all duration-300 ease-out' data={dataPie} />
              </div>
            </div>
          </div>


            {/* semi-projects */}
            <div id='project' className="w-full mb-20 overflow-hidden flex flex-col justify-center min-h-screen">
              <h1 className="text-3xl sm:text-4xl text-center font-bold mb-4 hover:scale-x-105 transition-all duration-300 ease-out cursor-pointer">What I did so far?</h1>
              <div className="flex justify-start items-center px-10 pb-5 w-full scroll-hidden">

                <section className="text-gray-600 body-font w-full container mx-auto">
                  <div className=" py-2  w-full flex flex-wrap">
                    <div className="flex w-full flex-wrap md:-m-2 -m-1">
                      <div className="flex flex-wrap w-1/2">
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/500x300" />
                        </div>
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/501x301" />
                        </div>
                        <div className="md:p-2 p-1 w-full">
                          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/600x360" />
                        </div>
                      </div>
                      <div className="flex flex-wrap w-1/2">
                        <div className="md:p-2 p-1 w-full">
                          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/601x361" />
                        </div>
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/502x302" />
                        </div>
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/503x303" />
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className=" py-2  w-full flex flex-wrap">
                    <div className="flex w-full flex-wrap md:-m-2 -m-1">
                      <div className="flex flex-wrap w-1/2">
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/500x300" />
                        </div>
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/501x301" />
                        </div>
                        <div className="md:p-2 p-1 w-full">
                          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/600x360" />
                        </div>
                      </div>
                      <div className="flex flex-wrap w-1/2">
                        <div className="md:p-2 p-1 w-full">
                          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/601x361" />
                        </div>
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/502x302" />
                        </div>
                        <div className="md:p-2 p-1 w-1/2">
                          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/503x303" />
                        </div>
                      </div>
                    </div>
                  </div>
                </section>

              </div>
            </div>

          </main>
        </div>

        <Footer />

      </div>
    </>
  )
}
