import React, { useContext, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Context } from '../context/context'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import ProjectItem from '../components/ProjectItem'
import Typewriter from 'typewriter-effect';
import Bg from '../components/Bg'
import { Doughnut } from 'react-chartjs-2'
import { Wave, Bitmoji } from '../components/Svgs'
import { motion } from 'framer-motion'
import { AiOutlineDownload } from 'react-icons/ai'
import { GiBrain, GiNotebook } from 'react-icons/gi'
import { FaAssistiveListeningSystems, FaLaptopCode, FaCheckCircle } from 'react-icons/fa'
import Quicknav from '../components/Quicknav'


export default function Home() {

  const { darkMode, aboutImgAnimation, aboutImgRef, aboutTextAnimation, aboutTextRef, experiencePieAnimation, experiencePieRef, experiencePieSmAnimation, experiencePieSmRef, experienceTextAnimation, experienceTextRef, experienceWorkflowAnimation, experienceWorkflowRef, experienceBarAnimation, experienceBarRef, experienceBarSmAnimation, experienceBarSmRef, projectItemRef, dataPie } = useContext(Context)

  return (
    <div className={`${darkMode?'dark-scroll':'light-scroll'}`}>

      <Head>
        <title>sambhav-kaushik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${darkMode ? '/teal.svg' : '/purple.svg'}`} />
      </Head>

      {/* bg */}
      <Bg />

      {/* design  */}
      <Wave />

      {/* quiknav */}
      <Quicknav />

      {/* app  */}
      <div className={`relative z-10 min-h-screen w-full transition-all duration-300 ease-in-out ${darkMode ? 'text-teal-500' : 'text-purple-600'}`}>

        <div className="max-w-7xl w-full mx-auto">

          <Navbar active={'home'} />

          <main className='w-full min-h-screen transition-all duration-300 ease-in-out'>

            {/* cover */}
            <div id='cover' className="w-full mb-10 mt-5 flex sm:flex-row sm:items-center sm:justify-evenly justify-center flex-col min-h-screen">

              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }} className="flex text-2xl font-bold sm:text-4xl flex-col justify-center px-10 py-5 w-full sm:w-1/2">

                <div className={`transition-all duration-300 ease-out`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>Hi, I'm </span>Sambhav Kaushik</div>
                <div className={`transition-all duration-300 ease-out`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I'm </span><Typewriter
                  options={{
                    strings: ['a Full-stack Web developer', 'a UI/UX designer', 'an App developer', 'a Data manager', 'a Logo designer', 'a 3-D modeler', 'an Animator', 'a Programmer'],
                    autoStart: true,
                    loop: true,
                  }}
                /></div>

                <a href={'/SOP.pdf'} download target='_blank' className={`my-5 flex items-center text-lg sm:text-xl font-bold ${darkMode ? 'text-teal-500' : 'text-purple-600'} transition-all duration-300 ease-in-out hover:underline underline-offset-4 cursor-pointer font-medium tracking-wider text-sm`}>Download my CV <AiOutlineDownload size={24} className={`ml-1`} /></a>

              </motion.div>
              <div className="w-full sm:w-1/2 py-5 max-w-sm mx-auto px-10">
                <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ duration: 0.3 }} className="w-full">
                  <div className={`${darkMode ? 'bg-teal-100' : 'bg-purple-100'} w-auto h-auto p-4 rounded-2xl flex items-center justify-center`}>
                  <Bitmoji />
                  </div>
                </motion.div>
              </div>
            </div>

            {/* semi-about  */}
            <div id='about' className="w-full pt-10 mb-10 flex items-center justify-center sm:flex-row flex-col min-h-screen">

              <div ref={aboutImgRef} className={`sm:w-1/2 w-11/12 mx-auto p-10 border-b border-l ${darkMode ? 'border-teal-500' : 'border-purple-600'}  max-w-sm mx-auto`}>
                <motion.img animate={aboutImgAnimation} className={`w-full rounded-lg`} src={'/photo2.jpg'} alt="" />
              </div>

              <div ref={aboutTextRef} className={`w-full sm:w-1/2`}>
                <motion.div ref={aboutTextRef} animate={aboutTextAnimation} className="my-auto flex flex-col justify-start px-10 py-5 w-full">
                  <h1 className="text-2xl sm:text-4xl font-bold mb-4 transition-all duration-300 ease-out">About Me</h1>
                  <p className={`text-sm:w-1/3 sm:text-base transition-all duration-300 ease-out`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a ni. <br /> Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a ni.</span></p>
                </motion.div>
              </div>
            </div>

            {/* semi-experience  */}
            <div ref={experienceTextRef} id='experience' className=" w-full pt-10 mb-10 overflow-hidden ">
              <div className="flex sm:flex-row sm:items-center flex-col w-full">
                <div className="w-full sm:w-2/3 px-10 py-5">
                  <motion.div animate={experienceTextAnimation} className=''>
                    <h1 className="sm:text-4xl text-2xl font-bold mb-4">My Experience {'&'} skills</h1>
                    <div className="text-sm:w-1/3 sm:text-base"><span className={`${darkMode ? 'text-white' : 'text-black'}`}>HTML, CSS, Bootstrap, TailwindCSS, MaterialUI, JavaScript, Python, ReactJS, NextJS, Strpi, ExpressJS, Django, Flask, PostgreDB, MongoDB, Mongoose, Block Chain, Ethereum, Polygon, Solidity, Rust, JSON, SanityDB, GROQ, Java, Pandas, Logo designing, Blender 3D, Animation, UX/UI designing and many more. Lorem ipsum dolor sit amet
                      <motion.div ref={experiencePieSmRef} animate={experiencePieSmAnimation} className="w-full sm:hidden block py-5 max-w-sm:w-1/3 mx-auto">
                        <Doughnut className='hover:scale-105 transition-all duration-300 ease-out' data={dataPie} />
                      </motion.div>
                      consectetur adipisicing elit. Inventore in iste, esse sunt ut, quas culpa harum laborum fugiat, nisi eos sequi maxime odio? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, incidunt beatae dicta assumenda harum ipsa reiciendis enim sequi rem quia corporis magnam, rerum impedit fuga alias adipisci hic unde veritatis! Voluptatem quod sit soluta sapiente atque praesentium exercitationem illum corrupti?
                      <div className={`w-full py-5 ${darkMode ? 'text-white' : 'text-black'} sm:hidden block`}>
                        <div ref={experienceBarSmRef} className="flex flex-col w-full">
                          <motion.div animate={experienceBarSmAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                            <p className="mb-2">Front-end development</p>
                            <div className={`w-10/12 bg-green-500 h-0.5 transition-all duration-300`}></div>
                          </motion.div>
                          <motion.div animate={experienceBarSmAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                            <p className="mb-2">Back-end development</p>
                            <div className={`w-full bg-red-500 h-0.5 transition-all duration-300`}></div>
                          </motion.div>
                          <motion.div animate={experienceBarSmAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                            <p className="mb-2">App development</p>
                            <div className={`w-11/12 bg-cyan-500 h-0.5 transition-all duration-300`}></div>
                          </motion.div>
                          <motion.div animate={experienceBarSmAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                            <p className="mb-2">Logo designing</p>
                            <div className={`w-9/12 bg-violet-500 h-0.5 transition-all duration-300`}></div>
                          </motion.div>
                          <motion.div animate={experienceBarSmAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                            <p className="mb-2">3D modelling</p>
                            <div className={`w-8/12 bg-orange-500 h-0.5 transition-all duration-300`}></div>
                          </motion.div>
                        </div>
                      </div>
                      Molestias a molestiae minus dolorum odit, obcaecati perspiciatis voluptatem cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt quas expedita sed nesciunt, ipsam nisi ab, labore praesentium aspernatur, earum cupiditate ad vero veritatis. Quia repellat sunt suscipit quas sed commodi earum fuga quibusdam quo, impedit voluptates aliquid mollitia repudiandae autem ex illum blanditiis nesciunt incidunt dolorem beatae, possimus perspiciatis?</span></div>
                  </motion.div>

                  <div className={`w-full mt-8 ${darkMode ? 'text-white' : 'text-black'} sm:block hidden`}>
                    <div ref={experienceBarRef} className="flex flex-col w-full">
                      <motion.div animate={experienceBarAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">Front-end development</p>
                        <div className={`w-10/12 bg-green-500 h-0.5 transition-all duration-300`}></div>
                      </motion.div>
                      <motion.div animate={experienceBarAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">Back-end development</p>
                        <div className={`w-full bg-red-500 h-0.5 transition-all duration-300`}></div>
                      </motion.div>
                      <motion.div animate={experienceBarAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">App development</p>
                        <div className={`w-11/12 bg-cyan-500 h-0.5 transition-all duration-300`}></div>
                      </motion.div>
                      <motion.div animate={experienceBarAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">Logo designing</p>
                        <div className={`w-9/12 bg-violet-500 h-0.5 transition-all duration-300`}></div>
                      </motion.div>
                      <motion.div animate={experienceBarAnimation} className={`w-full flex flex-col py-1 my-1  rounded-3xl hover:scale-x-105 transition-all duration-300 ease-out`}>
                        <p className="mb-2">3D modelling</p>
                        <div className={`w-8/12 bg-orange-500 h-0.5 transition-all duration-300`}></div>
                      </motion.div>
                    </div>
                  </div>

                </div>
                <div className="flex flex-row sm:flex-col justify-start items-start px-10 py-5 w-full sm:w-1/3 ">
                  <motion.div ref={experiencePieRef} animate={experiencePieAnimation} className="w-full hidden sm:block">
                    <Doughnut className='hover:scale-105 transition-all duration-300 ease-out' data={dataPie} />
                  </motion.div>
                </div>
              </div>

              <section ref={experienceWorkflowRef} className={`${darkMode?'text-white':'text-gray-900'} body-font`}>
                <motion.div animate={experienceWorkflowAnimation} className="px-5 py-5 mx-auto flex flex-col items-start flex-wrap">

                <p className={`text-lg mb-2 ${darkMode?'text-teal-500':'text-purple-600'} text-center font-medium w-full`}>My Workflow</p>


                  <div className="flex relative py-5 w-full sm:items-center sm:w-1/2 mx-auto">
                    <div className="h-full w-6 absolute inset-0 flex items-center justify-center">
                      <div className={`h-full w-1 ${darkMode?'bg-teal-500':'bg-purple-600'} pointer-events-none`}></div>
                    </div>
                    <div className={`flex-shrink-0 w-6 h-6 rounded-full mt-10 sm:mt-0 inline-flex items-center justify-center ${darkMode?'text-white bg-teal-500':'text-white bg-purple-600'} relative z-10 title-font font-medium text-sm`}>1</div>
                    <div className="flex-grow sm:pl-8 pl-6 flex sm:items-center items-start flex-col sm:flex-row">
                      <div className={`flex-shrink-0 w-16 h-16 shadow-lg ${darkMode?'bg-gray-800 text-teal-500':'bg-slate-100  text-purple-600'} rounded-full inline-flex items-center justify-center`}>
                        <FaAssistiveListeningSystems size={32} />
                      </div>
                      <div className="flex-grow sm:pl-6 mt-6 sm:mt-0">
                        <h2 className={`font-medium title-font mb-1 text-xl`}>Understand</h2>
                        <p className="leading-relaxed">My workflow starts with listening and understanding the problem carefully.</p>
                      </div>
                    </div>
                  </div>

                  <div className="flex relative py-5 w-full sm:items-center sm:w-1/2 mx-auto">
                    <div className="h-full w-6 absolute inset-0 flex items-center justify-center">
                      <div className={`h-full w-1 ${darkMode?'bg-teal-500':'bg-purple-600'} pointer-events-none`}></div>
                    </div>
                    <div className={`flex-shrink-0 w-6 h-6 rounded-full mt-10 sm:mt-0 inline-flex items-center justify-center ${darkMode?'text-white bg-teal-500':'text-white bg-purple-600'} relative z-10 title-font font-medium text-sm`}>2</div>
                    <div className="flex-grow sm:pl-8 pl-6 flex sm:items-center items-start flex-col sm:flex-row">
                      <div className={`flex-shrink-0 w-16 h-16 shadow-lg ${darkMode?'bg-gray-800 text-teal-500':'bg-slate-100  text-purple-600'} rounded-full inline-flex items-center justify-center`}>
                        <GiBrain size={32} />
                      </div>
                      <div className="flex-grow sm:pl-6 mt-6 sm:mt-0">
                        <h2 className={`font-medium title-font mb-1 text-xl`}>Figure out</h2>
                        <p className="leading-relaxed">I figure out all the possible solution and plausible difficulties ahead.</p>
                      </div>
                    </div>
                  </div>

                  <div className="flex relative py-5 w-full sm:items-center sm:w-1/2 mx-auto">
                    <div className="h-full w-6 absolute inset-0 flex items-center justify-center">
                      <div className={`h-full w-1 ${darkMode?'bg-teal-500':'bg-purple-600'} pointer-events-none`}></div>
                    </div>
                    <div className={`flex-shrink-0 w-6 h-6 rounded-full mt-10 sm:mt-0 inline-flex items-center justify-center ${darkMode?'text-white bg-teal-500':'text-white bg-purple-600'} relative z-10 title-font font-medium text-sm`}>3</div>
                    <div className="flex-grow sm:pl-8 pl-6 flex sm:items-center items-start flex-col sm:flex-row">
                      <div className={`flex-shrink-0 w-16 h-16 shadow-lg ${darkMode?'bg-gray-800 text-teal-500':'bg-slate-100  text-purple-600'} rounded-full inline-flex items-center justify-center`}>
                        <GiNotebook size={32}/>
                      </div>
                      <div className="flex-grow sm:pl-6 mt-6 sm:mt-0">
                        <h2 className={`font-medium title-font mb-1 text-xl`}>Action Plan</h2>
                        <p className="leading-relaxed">Then I make a plan and choose the tools to solve a problem.</p>
                      </div>
                    </div>
                  </div>

                  <div className="flex relative py-5 w-full sm:items-center sm:w-1/2 mx-auto">
                    <div className="h-full w-6 absolute inset-0 flex items-center justify-center">
                      <div className={`h-full w-1 ${darkMode?'bg-teal-500':'bg-purple-600'} pointer-events-none`}></div>
                    </div>
                    <div className={`flex-shrink-0 w-6 h-6 rounded-full mt-10 sm:mt-0 inline-flex items-center justify-center ${darkMode?'text-white bg-teal-500':'text-white bg-purple-600'} relative z-10 title-font font-medium text-sm`}>4</div>
                    <div className="flex-grow sm:pl-8 pl-6 flex sm:items-center items-start flex-col sm:flex-row">
                      <div className={`flex-shrink-0 w-16 h-16 shadow-lg ${darkMode?'bg-gray-800 text-teal-500':'bg-slate-100  text-purple-600'} rounded-full inline-flex items-center justify-center`}>
                        <FaLaptopCode size={32}/>
                      </div>
                      <div className="flex-grow sm:pl-6 mt-6 sm:mt-0">
                        <h2 className={`font-medium title-font mb-1 text-xl`}>Execution</h2>
                        <p className="leading-relaxed">Afterwards, I execute the plan efficiently.</p>
                      </div>
                    </div>
                  </div>

                  <div className="flex relative py-5 w-full sm:items-center sm:w-1/2 mx-auto">
                    <div className="h-full w-6 absolute inset-0 flex items-center justify-center">
                      <div className={`h-full w-1 ${darkMode?'bg-teal-500':'bg-purple-600'} pointer-events-none`}></div>
                    </div>
                    <div className={`flex-shrink-0 w-6 h-6 rounded-full mt-10 sm:mt-0 inline-flex items-center justify-center ${darkMode?'text-white bg-teal-500':'text-white bg-purple-600'} relative z-10 title-font font-medium text-sm`}>5</div>
                    <div className="flex-grow sm:pl-8 pl-6 flex sm:items-center items-start flex-col sm:flex-row">
                      <div className={`flex-shrink-0 w-16 h-16 shadow-lg ${darkMode?'bg-gray-800 text-teal-500':'bg-slate-100  text-purple-600'} rounded-full inline-flex items-center justify-center`}>
                        <FaCheckCircle size={32}/>
                      </div>
                      <div className="flex-grow sm:pl-6 mt-6 sm:mt-0">
                        <h2 className={`font-medium title-font mb-1 text-xl`}>Completion</h2>
                        <p className="leading-relaxed">Finally, I test the product and deliver it.</p>
                      </div>
                    </div>
                  </div>

                </motion.div>
              </section>

            </div>

            {/* semi-projects */}
            <div id='project' className="w-full pt-10 mb-10 overflow-hidden flex flex-col justify-center min-h-screen">
              <h1 className="text-2xl sm:text-4xl text-center font-bold mb-4 my-5">My Portfolio</h1>
              <div ref={projectItemRef} className="px-10 pb-5 w-full">

                <section className={`${darkMode ? 'text-white' : 'text-gray-900'} body-font`}>
                  <div className="w-full px-5 py-4 mx-auto">
                    <div className="flex flex-wrap -m-4">

                      <ProjectItem />
                      <ProjectItem />
                      <ProjectItem />

                    </div>
                  </div>
                </section>

                <section className={`${darkMode ? 'text-white' : 'text-gray-900'} body-font`}>
                  <div className="w-full px-5 py-4 mx-auto">
                    <div className="flex flex-wrap -m-4">

                      <ProjectItem />
                      <ProjectItem />
                      <ProjectItem />

                    </div>
                  </div>
                </section>

              </div>
            </div>

          </main>
        </div>

        <Footer />

      </div>

    </div>
  )
}
