import React, { useContext } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Context } from '../context/context'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Top from '../components/top'


export default function Project() {
  const { darkMode } = useContext(Context)
  return (
    <div className={`min-h-screen w-full ${darkMode ? 'bg-gradient-to-r from-[#1a1807] to-gray-900 text-yellow-400' : 'bg-gradient-to-r from-purple-300 to-white text-purple-600'}`}>
      <div className="max-w-7xl w-full mx-auto">
        <Top />
        <Head>
        <title>sambhav-kaushik-home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${darkMode ? '/yellow.svg' : '/purple.svg'}`} />
      </Head>

        <Navbar active={'project'} />

        <main className='w-full min-h-screen'>
        <h1 className="sm:text-4xl px-10 pt-5 text-3xl font-bold mb-4 hover:scale-x-105 transition-all duration-300 ease-out cursor-pointer">My Projects</h1>
          {/* project  */}
          <div id="project">

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great .</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view.</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view.</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view.</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view.</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view.</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view.</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          <div className={`w-full my-10 overflow-hidden flex sm:flex-row sm:items-center flex-col`}>
            <div className="px-10 py-5 w-full sm:w-3/5">
              <div className={`p-4 rounded-3xl ${darkMode?'bg-[#5e5e5e80]':'bg-[#e2e2e280]'} shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`}>
              <img src="/wp.jpg" alt="" className={`rounded-3xl shadow-lg ${darkMode ? 'shadow-yellow-400/40' : 'shadow-purple-600/50'}`} />
              </div>
            </div>
            <div className="px-10 py-5 w-full sm:w-2/5">
            <h1 className="sm:text-3xl text-2xl font-bold mb-4 transition-all duration-300 ease-out cursor-pointer hover:scale-105">Makeup Website</h1>
            <p className={`text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}>I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view, which is a nice touch.I only use MongoDB as my database. At least for now. Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well.  Robo3T is a great client for MongoDB, especially for development purpose. Connects easily to your local Mongo, and support SSH tunnels as well. It has a list and a table view.</span></p>
            <p className={`text-right pt-4 text-sm sm:text-base`}><span className={`${darkMode ? 'text-white' : 'text-gray-900'}`}><a onClick={() => {
                        setIsLoading(true)
                        setTimeout(() => {
                            router.push('/about')
                        }, 500);
                    }} className={`${darkMode?'text-yellow-400':'text-purple-600'} cursor-pointer hover:underline underline-offset-4`}>Visit Website</a></span></p>
            </div>
          </div>

          </div>
        </main>

        <Footer />
      </div>
    </div>
  )
}